backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Bài viết"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}"

    fields:
      - {label: "Tiêu đề", name: "title", widget: "string"}
      - {label: "Tiêu đề SEO", name: "seo_title", widget: "string", required: false}
      - {label: "Mô tả SEO", name: "seo_description", widget: "text", required: false}
      - {label: "Slug (đường dẫn)", name: "slug", widget: "string", required: false}
      - {label: "Ngày đăng", name: "date", widget: "datetime"}
      - {label: "Ảnh đại diện", name: "thumbnail", widget: "image", required: false}
      - {label: "Tóm tắt", name: "description", widget: "text"}
      - {label: "Nội dung", name: "body", widget: "markdown"}
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          allow_add: true,
          field: {label: "Tag", name: "tag", widget: "string"}
        }
      - {label: "Danh mục", name: "category", widget: "select", options: ["Công nghệ", "Cuộc sống", "Du lịch"], default: "Công nghệ"}

  - name: "pages"
    label: "Trang"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"

    fields:
      - {label: "Tiêu đề", name: "title", widget: "string"}
      - {label: "Tiêu đề SEO", name: "seo_title", widget: "string", required: false}
      - {label: "Mô tả SEO", name: "seo_description", widget: "text", required: false}
      - {label: "Slug (đường dẫn)", name: "slug", widget: "string", required: false}
      - {label: "Nội dung", name: "body", widget: "markdown"}
