backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Bài viết"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string", required: true }
      - { label: "Ngày đăng", name: "date", widget: "datetime", required: true }
      - { label: "Ảnh minh họa", name: "thumbnail", widget: "image" }
      - { label: "Tóm tắt", name: "description", widget: "text" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
      - { label: "Thể loại", name: "tags", widget: "list", default: ["Anime"] }
